[gcp_service_account]
type = "service_account"
project_id = "tonal-envelope-468301-n2"
private_key_id = "71040079317cd4487c5c9eed6aca25790a4d9c33"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDaDEpdrKJ/LMYm
xnKQK0uNJa+aOg1oDpwZX4jJql3Vh0Q1XXuA0uq2qZRTxM6WmvZ/3dP1Go/sIxZZ
RljzKuawkz8Lg6GoP4B8aBJingxPej+6QoMHlwEAP0HRHkgFgqUZ6xsPvs9hiM5K
MhccyU+LhUM0gvFgV9hlDIZMcxB7eO23MrrivBgol287wegeef1iw+DtL3g+3vsb
8UQoOZEDnvfMou45EwGUPiyVrwU21/X5JeT1cVzykCEO3n49Onrjy/B+vXubn0MD
se6YBQqUURwcTk6MQ5Op/Z2K+7PUbYHuffKsbFSFBZXr3P5B5lkdzYfE8OBGX6J0
Kz6OtC+1AgMBAAECggEAG3QbsuKnDQMaqcwnpX5GA24Ax5bSlEzum4U7SETijp16
2Ys9HxGvSrNcQRXQ+wZkzeGkq8Id59ndGP1x+p/mrsnDUNRQeMoSB9fkpLUIkMMw
Hef87mo1To4oX8eDwunZlsNSw28/ViTu8EmRPmccVFFBjm2ELaCx1rs2d46vPxRV
mPw+rmACq46Q2SYuB8otxXMFaq6FYhtm5RCitjpdj526bVLsMe2utYul2ipFsaqj
DURsV8Upzm8MsAV8pSQm+rvsnlZIPXgLEep44agxOyf5lTds9Br7/mMPfKr6pQZA
DCIMJjfdy7iJhWyNOqagI1A32sjtjSAuQeAOjU3V4QKBgQD9lyyWGmE8HOusn/8L
DjVpnrDbxfBJ700zLIIb0xMEA4xFyl6zzbYvNgqwRzsvYq1EDplNpI6ouoUF3DWL
oulKIX/Fd13wyNcYBtk9pORjYM1aDqENzYzDEwRc/nQVt64LLW6mDJS6vE7aG1B3
MNLpTk5YnBfYF2JroeKifCU2ZQKBgQDcHqnu55NGyKp1yOK8XU+mr95AV5HUHj81
dBBOe077gr1sN546659Rn8K6x8k8Kl/BglKWSUDYj7FJPH1GeVge6GYYAKjR9IMu
8dDdH/S1zZOmlzV2Hzff06v1RqnMD0lV0zjFQWsLhIrThMjRvJ2khfkLO5/bzRVm
yKf/Sy6XEQKBgDDY/e2sBy7dI0iNSUOH6SH/P3IWHsMfJW/GEwnpDrCnPk3zPWrF
JWLSthxenDf0eguyBDXAjPpTc2w9jtLm/qkY6tPOunm3Njeamh4VtSivbN78Emnm
PkcVUrHXEeVdDFl61uWFZuDRhR7eRBGxhe8K9mx7JNyrJHo3JMDHySNBAoGBALjj
DKs9WcgfroXmaQP8gHWqzMxQgY2gpkj4puW0zv+UrhRilwY4eQZvYXnPa6ickveP
xlyzRMNh1nCEXVk/fRPg8jgA/cv0S+e3d070k2/NL9LCuUXxLNZVDd+kLeTXhiqP
kuSkcQwolQ7bPm5ktijF2wxjVX+iv/IoYmuds5FxAoGAZ090j9lQcxtojfRJ+f6j
tfVt9f2wju9mZmevyMracLz0c6KE86zqv1X9G7HWrP0J6hDstSY12+FConounjtu
aaiM2yMrXrF31oA1RQ/ZyjbASjjAsnsezRpnKQhVq+ewn1eVj/NZ/gfPSWvfjvTB
/HIi7xL555vzCUdL0TRpzss=
-----END PRIVATE KEY-----
"""
client_email = "soso-844@tonal-envelope-468301-n2.iam.gserviceaccount.com"
client_id = "101519334907406763762"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/soso-844%40tonal-envelope-468301-n2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
